import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerAgentCard } from './agentcard.js';
import { registerApm } from './apm.js';
import { registerApmExecute } from './apm-execute.js';
import { registerBacktest } from './backtest.js';
import { registerBrokers } from './brokers.js';
import { registerCopyTrader } from './copytrader.js';
import { registerCrawl } from './crawl.js';
import { registerDiscovery } from './discovery.js';
import { registerEquitiesHeatmap } from './equities-heatmap.js';
import { registerFederal } from './federal.js';
import { registerForge } from './forge.js';
import { registerFtd } from './ftd.js';
import { registerGhost } from './ghost.js';
import { registerLaunchpad } from './launchpad.js';
import { registerLeviathan } from './leviathan.js';
import { registerNexus } from './nexus.js';
import { registerProof402 } from './proof402.js';
import { registerRails } from './rails.js';
import { registerShadow } from './shadow.js';
import { registerSqueezeOS } from './squeezeos.js';
import { registerXdeo } from './xdeo.js';
import { registerXmit } from './xmit.js';

export async function registerTools(server: McpServer): Promise<void> {
  registerDiscovery(server);
  registerApm(server);
  registerApmExecute(server);
  registerAgentCard(server);
  registerBacktest(server);
  registerBrokers(server);
  registerCopyTrader(server);
  registerCrawl(server);
  registerEquitiesHeatmap(server);
  registerFederal(server);
  registerForge(server);
  registerFtd(server);
  registerGhost(server);
  registerLaunchpad(server);
  await registerLeviathan(server);
  registerNexus(server);
  registerProof402(server);
  registerRails(server);
  registerShadow(server);
  registerSqueezeOS(server);
  registerXdeo(server);
  await registerXmit(server);
}
